### PR TITLE
Subscribe and respond to Pull Request event hook

### PR DESCRIPTION
**Pull request by jugglinmike**
Each time the contents of a pull request changes, re-check all the commits in
that pull request.

I started by implementing some of the pending tests just to further protect
against possible ~~refactorings~~ regressions. Next, I refactored some of the internals to
better support code re-use for the functionality in question. You'll note this
second commit adds no new tests. This is intentional; the commit does not
change any functionality. The final commit introduces the new functionality and
a corresponding test (I renamed the existing test file to better distintinguish
between the two).

I'd really like to use CLAHub for my open source project, but pull request
integration is a hard requirement. If there's anything I can do to help get
this into `master`, please don't hesitate to tell me!

Resolves gh-47 and gh-51

### CODE REVIEW

**Comment by jugglinmike** [comment]
Is there anything more I can do to help move this forward?

**Comment by jasonm** [comment]
Hey @jugglinmike thanks for adding pending tests, and the very readable PR format.

I assume I'll need to backfill the `pull_request` event on existing repo hooks to get this functionality applied to them.

There was one piece I had to readd (coming as b89fbda8570e3ccbad8c8f95e0518134a4e3cc7a) which was checking if an author is present on a commit.  This was previously implemented here: https://github.com/clahub/clahub/blob/2695de1ba76ebd759bd4e0b5f7cd8078fd4a0ddc/app/models/push_status_checker.rb#L46-47 but there was no test to motivate it.  I'd like to add a test to motivate it, but would like even more to get your changes deployed.

**Comment by jasonm** [comment]
This is live.  I've tested this a fair amount against PRs on jasonm/clahub-test and jasonm/clahub-test2.  @jugglinmike can you let me know if this also works for you?

**Comment by jasonm** [comment]
:saxophone:  :boom:  ... and thanks again for the PR!

**Pull request merged**
