### PR TITLE
Organization-level agreements

### PR DESCRIPTION
**Pull request by esteve**
This branch adds support for creating agreements that cover all the repos in an organization account. This adds a new ```$ORGANIZATION/@ALL``` entry to the repo drop-down menu that, when selected, allows users to create agreements for all the repositories in an organization they are administrators of.

### CODE REVIEW

**Comment by andrerom** [comment]
> @jasonm I haven't thought of that usecase, I think the creator of the CLA should create it for any new repository, I'm not a lawyer, but it seems that legally speaking you can't create agreeements beforehand.

Actually this is quite normal in CLA's that you (or the company you work on) can sign a CLA towards another company (so full organization in github speak) with no limitations. So shouldn't be any need to track it by repo if CLA is _signed_ towards the org.

**Comment by robinzimmermann** [comment]
It looks like GitHub have recently added [Organization webhooks](https://github.com/blog/1933-introducing-organization-webhooks).

It will notify you when a new repository is created within the GH organization. Have a look in the [Webhooks API](https://developer.github.com/webhooks/) and scroll down to `repository` in the **Events** section.

**Comment by robinzimmermann** [comment]
We are really keen to use this organization-based feature!

Let us know if we can help in any way.

**Comment by klinebch** [comment]
+1 on the value of this use case.  We have too many repositories to process CLA for every one.  It would be much easier to do it once for the organization.

**Comment by mzagaja** [comment]
Hi @esteve, I'm one of the new maintainers from the Berkman Center I just wanted to check in since it's been a year since it was put in this pull request no longer cleanly merges after a refactor and ask whether you want to update it to do so (in which case I'll accept the update) or if I should close this out and consider this a template for potentially adding this feature in the future. The same question also applies to https://github.com/clahub/clahub/pull/84. Let me know and I'm happy to proceed with whatever way makes the most sense. Thanks so much for contributing these.

**Comment by mzagaja** [comment]
Going to close this and leave #82 open as a feature request.

**Pull request closed without merging**
